
def translate_sentence_to_spanish(sentence, translation_dict):
    # Function to translate an English sentence to Spanish.
    # It splits the input sentence into words, looks up each word in the translation_dict,
    # and constructs a translated sentence.
    words = sentence.split()
    translated_words = [translation_dict.get(word, word) for word in words]
    translated_sentence = ' '.join(translated_words)
    return translated_sentence

def save_translation(translation, saved_translations):
    # The Function of this is to save a translation in the list of saved_translations.
    saved_translations.append(translation)

def show_saved_translations(saved_translations):
    # The Function of this is to display the list of saved translations.
    if not saved_translations:
        print("No translations have been saved yet.")
    else:
        print("Saved Translations:")
        for i, translation in enumerate(saved_translations, start=1):
            print(f"{i}. {translation}")
# this is the 'main' or main menu that shows every time you press a option
def main():
    print("Welcome to the ME021 Translator Project!")
    print("f")
    print("Project Description: This project translates English words to Spanish.")

    translation_dict = {
        #I created a English-to-Spanish translation dictionary.
        #Because I was not able to use a external webside or dictionary.
        "I": "Yo",
        "love": "amo",
        "dogs": "perros",
        "hello": "hola",
        "world": "mundo",
        "planet": "planeta",
        "hey": "oye",
        "globe": "globo",
        "greetings": "saludos",
        "universe": "universo",
        "good day": "buen dia",
        "erth": "tierra",
        "dog": "perro",
        "cat": "gato",
        "elephant": "elefante",
        "lion": "león",
        "bird": "pájaro",
        "fish": "pez",
        "horse": "caballo",
        "cow": "vaca",
        "snake": "serpiente",
        "turtle": "tortuga",
        "rabbit": "conejo",
        "deer": "ciervo",
        "bear": "oso",
        "wolf": "lobo",
        "monkey": "mono",
        "gorilla": "gorila",
        "dolphin": "delfín",
        "whale": "ballena",
        "penguin": "pingüino",
        "seal": "foca",
        "tiger": "tigre",
        "giraffe": "jirafa",
        "octopus": "pulpo",
        "sharks": "tiburón",
        "apple": "manzana",
        "banana": "plátano",
        "orange": "naranja",
        "grape": "uva",
        "strawberry": "fresa",
        "blueberry": "arándano",
        "cherry": "cereza",
        "watermelon": "sandía",
        "pineapple": "piña",
        "peach": "durazno",
        "plum": "ciruela",
        "lemon": "limón",
        "lime": "lima",
        "avocado": "aguacate",
        "pear": "pera",
        "apricot": "albaricoque",
        "kiwi": "kiwi",
        "mango": "mango",
        "pomegranate": "granada",
        "fig": "higo",
        "coconut": "coco",
        "raspberry": "frambruesa",
        "blackberry": "zarzamora",
        "papaya": "papaya",
        "melon": "melón",
        "cantaloupe": "cantalupo",
        "cranberry": "arándano",
        "elderberry": "saúco",
        "grapefruit": "toronja",
        "vegetable": "verdura",
        "carrot": "zanahoria",
        "potato": "patata",
        "tomato": "tomate",
        "lettuce": "lechuga",
        "cucumber": "pepino",
        "broccoli": "brócoli",
        "spinach": "espinacas",
        "bell pepper": "pimiento",
        "onion": "cebolla",
        "garlic": "ajo",
        "celery": "apio",
        "zucchini": "calabacín",
        "eggplant": "berenjena",
        "peas": "guisantes",
        "green bean": "judía verde",
        "corn": "maíz",
        "asparagus": "espárragos",
        "cauliflower": "coliflor",
        "cabbage": "repollo",
        "lettuce": "lechuga",
        "broccoli": "brócoli",
        "meat": "carne",
        "beef": "res",
        "chicken": "pollo",
        "pork": "cerdo",
        "lamb": "cordero",
        "fish": "pescado",
        "shrimp": "camarón",
        "lobster": "langosta",
        "crab": "cangrejo",
        "sausage": "salchicha",
        "bacon": "tocino",
        "ham": "jamón",
        "steak": "filete",
        "bread": "pan",
        "rice": "arroz",
        "pasta": "pasta",
        "noodles": "fideos",
        "spaghetti": "espagueti",
        "rice": "arroz",
        "pizza": "pizza",
        "hamburger": "hamburguesa",
        "sandwich": "sándwich",
        "soup": "sopa",
        "salad": "ensalada",
        "dessert": "postre",
        "cake": "pastel",
        "cookie": "galleta",
        "ice cream": "helado",
        "chocolate": "chocolate",
        "candy": "caramelo",
        "pie": "pastel",
        "beverage": "bebida",
        "coffee": "café",
        "tea": "té",
        "juice": "jugo",
        "milk": "leche",
        "soda": "refresco",
        "water": "agua",
        "beer": "cerveza",
        "wine": "vino",
        "cocktail": "cóctel",
        "whiskey": "whisky",
        "vodka": "vodka",
        "rum": "ron",
        "gin": "ginebra",
        "fruit": "fruta",
        "grain": "grano",
        "nut": "nuez",
        "dairy": "lácteo",
        "cheese": "queso",
        "butter": "mantequilla",
        "yogurt": "yogur",
        "egg": "huevo",
        "sugar": "azúcar",
        "salt": "sal",
        "pepper": "pimienta",
        "spice": "especia",
        "herb": "hierba",
        "garlic": "ajo",
        "ginger": "jengibre",
        "vanilla": "vainilla",
        "onion": "cebolla",
        "garlic": "ajo",
        "cinnamon": "canela",
        "parsley": "perejil",
        "rosemary": "romero",
        "thyme": "tomillo",
        "basil": "albahaca",
        "coriander": "cilantro",
        "mint": "menta",
        "oregano": "orégano",
        "beverage": "bebida",
        "coffee": "café",
        "tea": "té",
        "juice": "jugo",
        "milk": "leche",
        "soda": "refresco",
        "water": "agua",
        "beer": "cerveza",
        "wine": "vino",
        "cocktail": "cóctel",
        "whiskey": "whisky",
        "vodka": "vodka",
        "rum": "ron",
        "gin": "ginebra",
        "fruit": "fruta",
        "grain": "grano",
        "nut": "nuez",
        "dairy": "lácteo",
        "cheese": "queso",
        "butter": "mantequilla",
        "yogurt": "yogur",
        "egg": "huevo",
        "sugar": "azúcar",
        "salt": "sal",
        "pepper": "pimienta",
        "spice": "especia",
        "herb": "hierba",
        "garlic": "ajo",
        "ginger": "jengibre",
        "vanilla": "vainilla",
        "onion": "cebolla",
        "garlic": "ajo",
        "cinnamon": "canela",
        "parsley": "perejil",
        "rosemary": "romero",
        "thyme": "tomillo",
        "basil": "albahaca",
        "coriander": "cilantro",
        "mint": "menta",
        "oregano": "orégano",
        "bicycle": "bicicleta",
        "car": "coche",
        "bus": "autobús",
        "train": "tren",
        "airplane": "avión",
        "ship": "barco",
        "boat": "bote",
        "motorcycle": "motocicleta",
        "taxi": "taxi",
        "truck": "camión",
        "helicopter": "helicóptero",
        "subway": "metro",
        "bathroom": "baño",
        "toilet": "inodoro",
        "shower": "ducha",
        "sink": "lavabo",
        "bed": "cama",
        "table": "mesa",
        "chair": "silla",
        "sofa": "sofá",
        "lamp": "lámpara",
        "window": "ventana",
        "door": "puerta",
        "kitchen": "cocina",
        "refrigerator": "nevera",
        "microwave": "microondas",
        "oven": "horno",
        "television": "televisión",
        "computer": "computadora",
        "phone": "teléfono",
        "internet": "internet",
        "book": "libro",
        "magazine": "revista",
        "newspaper": "periódico",
        "pen": "pluma",
        "pencil": "lápiz",
        "notebook": "cuaderno",
        "backpack": "mochila",
        "glasses": "gafas",
        "watch": "reloj",
        "shoe": "zapato",
        "shirt": "camisa",
        "pants": "pantalones",
        "hat": "sombrero",
        "jacket": "chaqueta",
        "socks": "calcetines",
        "gloves": "guantes",
        "umbrella": "paraguas",
        "wallet": "billetera",
        "coin": "moneda",
        "cash": "efectivo",
        "credit card": "tarjeta de crédito",
        "receipt": "recibo",
        "shopping": "compras",
        "groceries": "comestibles",
        "market": "mercado",
        "store": "tienda",
        "restaurant": "restaurante",
        "cafe": "cafetería",
        "menu": "menú",
        "breakfast": "desayuno",
        "lunch": "almuerzo",
        "dinner": "cena",
        "snack": "tentempié",
        "vegetarian": "vegetariano",
        "vegan": "vegano",
        "allergy": "alergia",
        "medicine": "medicina",
        "hospital": "hospital",
        "doctor": "médico",
        "nurse": "enfermero",
        "pharmacy": "farmacia",
        "emergency": "emergencia",
        "appointment": "cita",
        "symptom": "síntoma",
        "injury": "lesión",
        "accident": "accidente",
        "health": "salud",
        "exercise": "ejercicio",
        "yoga": "yoga",
        "swimming": "natación",
        "running": "correr",
        "walking": "caminar",
        "cycling": "ciclismo",
        "hiking": "senderismo",
        "climbing": "escalada",
        "sun": "sol",
        "moon": "luna",
        "star": "estrella",
        "sky": "cielo",
        "earth": "tierra",
        "planet": "planeta",
        "space": "espacio",
        "galaxy": "galaxia",
        "solar system": "sistema solar",
        "universe": "universo",
        "astronomy": "astronomía",
        "constellation": "constelación",
        "telescope": "telescopio",
        "satellite": "satélite",
        "asteroid": "asteroide",
        "comet": "cometa",
        "cosmic": "cósmico",
        "alien": "extraterrestre",
        "sunrise": "amanecer",
        "sunset": "atardecer",
        "weather": "clima",
        "rain": "lluvia",
        "snow": "nieve",
        "wind": "viento",
        "cloud": "nube",
        "thunder": "trueno",
        "lightning": "relámpago",
        "rainbow": "arcoíris",
        "season": "estación",
        "spring": "primavera",
        "summer": "verano",
        "autumn": "otoño",
        "winter": "invierno",
        "day": "día",
        "night": "noche",
        "morning": "mañana",
        "afternoon": "tarde",
        "evening": "tarde",
        "midnight": "medianoche",
        "hour": "hora",
        "minute": "minuto",
        "second": "segundo",
        "clock": "reloj",
        "calendar": "calendario",
        "week": "semana",
        "month": "mes",
        "year": "año",
        "past": "pasado",
        "present": "presente",
        "future": "futuro",
        "history": "historia",
        "ancient": "antiguo",
        "modern": "moderno",
        "technology": "tecnología",
        "computer": "computadora",
        "internet": "internet",
        "email": "correo electrónico",
        "website": "sitio web",
        "programming": "programación",
        "coding": "codificación",
        "algorithm": "algoritmo",
        "database": "base de datos",
        "software": "software",
        "hardware": "hardware",
        "mouse": "ratón",
        "keyboard": "teclado",
        "screen": "pantalla",
        "printer": "impresora",
        "camera": "cámara",
        "phone": "teléfono",
        "social media": "redes sociales",
        "music": "música",
        "song": "canción",
        "art": "arte",
        "painting": "pintura",
        "sculpture": "escultura",
        "photography": "fotografía",
        "dance": "baile",
        "theater": "teatro",
        "film": "cine",
        "actor": "actor",
        "actress": "actriz",
        "director": "director",
        "producer": "productor",
        "script": "guion",
        "camera": "cámara",
        "special effects": "efectos especiales",
        "literature": "literatura",
        "book": "libro",
        "novel": "novela",
        "poetry": "poesía",
        "fiction": "ficción",
        "non-fiction": "no ficción",
        "story": "historia",
        "character": "personaje",
        "plot": "trama",
        "theme": "tema",
        "education": "educación",
        "school": "escuela",
        "teacher": "profesor",
        "student": "estudiante",
        "lesson": "lección",
        "subject": "asignatura",
        "exam": "examen",
        "grade": "nota",
        "degree": "grado",
        "university": "universidad",
        "research": "investigación",
        "experiment": "experimento",
        "lab": "laboratorio",
        "result": "resultado",
        "theory": "teoría",
        "I": "yo",
        "you": "tú",
        "he": "él",
        "she": "ella",
        "it": "eso (neutral)",
        "we": "nosotros",
        "they": "ellos / ellas",
        "me": "me",
        "him": "lo",
        "her": "la",
        "us": "nos",
        "them": "los / las",
        "myself": "yo mismo",
        "yourself": "tú mismo / usted mismo ",
        "himself": "él mismo",
        "herself": "ella misma",
        "itself": "eso mismo ",
        "ourselves": "nosotros mismos",
        "a": "un",
        "an": "un",
        "the": "el",
        "this": "esto",
        "that": "eso",
        "these": "estos",
        "those": "esos",
        "some": "algunos",
        "any": "cualquier",
        "every": "cada",
        "all": "todos",
        "many": "muchos",
        "few": "pocos",
        "several": "varios",
        "more": "más",
        "less": "menos",
        "much": "mucho",
        "little": "poco",
        "enough": "suficiente",
        "only": "solo",
        "just": "justo",
        "both": "ambos",
        "either": "cualquiera",
        "neither": "ninguno",
        "all": "todo",
        "any": "cualquier",
        "none": "ningún",
        "such": "tal",
        "every": "cada",
        "another": "otro",
        "a": "un",
        "an": "un",
        "the": "el",
        "this": "esto",
        "that": "eso",
        "these": "estos",
        "those": "esos",
        "some": "algunos",
        "any": "cualquier",
        "every": "cada",
        "all": "todos",
        "many": "muchos",
        "few": "pocos",
        "several": "varios",
        "more": "más",
        "less": "menos",
        "much": "mucho",
        "little": "poco",
        "enough": "suficiente",
        "only": "solo",
        "just": "justo",
        "both": "ambos",
        "either": "cualquiera",
        "neither": "ninguno",
        "all": "todo",
        "any": "cualquier",
        "none": "ningún",
        "such": "tal",
        "every": "cada",
        "another": "otro",
        "most": "la mayoría",
        "how": "cómo",
        "like": "como",
        "a": "un",
        "an": "un",
        "the": "el",
        "this": "esto",
        "that": "eso",
        "these": "estos",
        "those": "esos",
        "some": "algunos",
        "any": "cualquier",
        "every": "cada",
        "all": "todos",
        "many": "muchos",
        "few": "pocos",
        "several": "varios",
        "more": "más",
        "less": "menos",
        "much": "mucho",
        "little": "poco",
        "enough": "suficiente",
        "only": "solo",
        "just": "justo",
        "both": "ambos",
        "either": "cualquiera",
        "neither": "ninguno",
        "all": "todo",
        "any": "cualquier",
        "none": "ningún",
        "such": "tal",
        "every": "cada",
        "another": "otro",
        "most": "la mayoría",
        "how": "cómo",
        "like": "como",
        "know": "saber",
        "cats": "gatos",
        "dogs": "perros",
        "elephants": "elefantes",
        "lions": "leones",
        "birds": "pájaros",
        "fish": "peces",
        "horses": "caballos",
        "cows": "vacas",
        "snakes": "serpientes",
        "turtles": "tortugas",
        "rabbits": "conejos",
        "deer": "ciervos",
        "bears": "osos",
        "wolves": "lobos",
        "monkeys": "monos",
        "gorillas": "gorilas",
        "dolphins": "delfines",
        "whales": "ballenas",
        "penguins": "pingüinos",
        "seals": "focas",
        "tigers": "tigres",
        "giraffes": "jirafas",
        "octopuses": "pulpos",
        "apple": "manzana",
        "banana": "plátano",
        "orange": "naranja",
        "grape": "uva",
        "strawberry": "fresa",
        "blueberry": "arándano",
        "cherry": "cereza",
        "watermelon": "sandía",
        "pineapple": "piña",
        "peach": "durazno",
        "plum": "ciruela",
        "lemon": "limón",
        "lime": "lima",
        "avocado": "aguacate",
        "pear": "pera",
        "apricot": "albaricoque",
        "kiwi": "kiwi",
        "mango": "mango",
        "pomegranate": "granada",
        "fig": "higo",
        "coconut": "coco",
        "raspberry": "frambuesa",
        "blackberry": "zarzamora",
        "papaya": "papaya",
        "melon": "melón",
        "cantaloupe": "cantalupo",
        "cranberry": "arándano",
        "elderberry": "saúco",
        "grapefruit": "toronja",
        "vegetable": "verdura",
        "carrot": "zanahoria",
        "potato": "patata",
        "tomato": "tomate",
        "lettuce": "lechuga",
        "cucumber": "pepino",
        "broccoli": "brócoli",
        "spinach": "espinacas",
        "bell pepper": "pimiento",
        "onion": "cebolla",
        "garlic": "ajo",
        "celery": "apio",
        "zucchini": "calabacín",
        "eggplant": "berenjena",
        "peas": "guisantes",
        "green bean": "judía verde",
        "corn": "maíz",
        "asparagus": "espárragos",
        "cauliflower": "coliflor",
        "cabbage": "repollo",
        "lettuce": "lechuga",
        "broccoli": "brócoli",
        "meat": "carne",
        "beef": "res",
        "chicken": "pollo",
        "pork": "cerdo",
        "lamb": "cordero",
        "fish": "pescado",
        "shrimp": "camarón",
        "lobster": "langosta",
        "crab": "cangrejo",
        "sausage": "salchicha",
        "bacon": "tocino",
        "ham": "jamón",
        "steak": "filete",
        "bread": "pan",
        "rice": "arroz",
        "pasta": "pasta",
        "noodles": "fideos",
        "spaghetti": "espagueti",
        "pizza": "pizza",
        "hamburger": "hamburguesa",
        "sandwich": "sándwich",
        "soup": "sopa",
        "salad": "ensalada",
        "dessert": "postre",
        "cake": "pastel",
        "cookie": "galleta",
        "where": "dónde",
        "when": "cuándo",
        "why": "por qué",
        "what": "qué",
        "which": "cuál",
        "who": "quién",
        "whom": "a quién",
        "whose": "de quién",
        "here": "aquí",
        "there": "allí",
        "now": "ahora",
        "soon": "pronto",
        "later": "más tarde",
        "yesterday": "ayer",
        "today": "hoy",
        "tomorrow": "mañana",
        "please": "por favor",
        "thank you": "gracias",
        "you're welcome": "de nada",
        "yes": "sí",
        "no": "no",
        "maybe": "quizás",
        "good": "bueno",
        "bad": "malo",
        "happy": "feliz",
        "sad": "triste",
        "angry": "enojado",
        "hungry": "hambriento",
        "thirsty": "sediento",
        "tired": "cansado",
        "sleepy": "soñoliento",
        "hot": "caliente",
        "cold": "frío",
        "beautiful": "hermoso",
        "ugly": "feo",
        "big": "grande",
        "small": "pequeño",
        "new": "nuevo",
        "old": "viejo",
        "fast": "rápido",
        "slow": "lento",
        "loud": "ruidoso",
        "quiet": "silencioso",
        "expensive": "caro",
        "cheap": "barato",
        "hard": "difícil",
        "easy": "fácil",
        "right": "derecho",
        "left": "izquierdo",
        "up": "arriba",
        "down": "abajo",
        "in": "en",
        "out": "fuera",
        "near": "cerca",
        "far": "lejos",
        "good morning": "buenos días",
        "good afternoon": "buenas tardes",
        "good evening": "buenas noches",
        "good night": "buenas noches",
        "hello": "hola",
        "goodbye": "adiós",
        "please": "por favor",
        "excuse me": "disculpe",
        "I'm sorry": "lo siento",
        "yes": "sí",
        "no": "no",
        "maybe": "quizás",
        "I don't know": "no sé",
        "love": "amor",
        "miss": "extrañar",
        "need": "necesitar",
        "help": "ayuda",
        "please": "por favor",
        "understand": "entender",
        "name": "nombre",
        "How": "Cómo",
        "are": "estás",
        "fine": "bien",
        "not": "no",
        "feeling": "siento",
        "well": "bien",
        "time": "hora",
        "Can": "Puedes",
        "Where": "Dónde",
        "from": "eres",
        "What": "qué",
        "is": "esto",
        "much": "cuánto",
        "lost": "perdido",
        "What's": "está",
        "the": "el",
        "weather": "clima",
        "bathroom": "baño",
        "doctor": "médico",
        "hungry": "hambre",
    }

    saved_translations = []  # also the List to store saved translations
# here are my options that shows every time we chose a option
    # In coding, 'if' is used to check a condition and execute a block of code
    # if that condition is true. 'Elif,' short for 'else if,' allows you to check
    # additional conditions if the previous 'if' or 'elif' conditions are false.
    # 'Else' provides a fallback option, executing a block of code when none of
    # the preceding conditions are met.
    while True:
        print("Choose an option:")
        print("1. Translate English sentence to Spanish")
        print("2. Save Translation")
        print("3. Show Saved Translations")
        print("4. Exit")

        choice = input("Enter your choice (1-4): ")

        if choice == '1':
            sentence = input("Enter an English sentence to translate to Spanish: ")
            translation = translate_sentence_to_spanish(sentence, translation_dict)
            print(f"Translation: {translation}")
        elif choice == '2':
            if 'translation' in locals():  # Check if translation exists
                save_translation(translation, saved_translations)
                print("Translation saved.")
            else:
                print("No translation to save. Please translate a sentence first.")
        elif choice == '3':
            show_saved_translations(saved_translations)
        elif choice == '4':
            print("Exiting the translator. Goodbye!")
            break
        else:
            print("Invalid choice. Please choose a valid option.")

if __name__ == "__main__":
    main()
#My English-to-Spanish translation project starts with a friendly introduction
# and relies on a comprehensive dictionary for word translations. It offers a
# user-friendly menu with various options, including translating English sentences
# to Spanish, saving translations for future reference, displaying saved translations,
# and allowing the user to exit the program. Inside the translation function, the magic
# happens as it transforms English sentences into their Spanish equivalents.
# Users can save their favorite translations for later, and the project keeps track
# of these saved translations. The entire program runs in a loop, ensuring the user can
# continue to interact, and it gracefully handles invalid choices by providing informative
# error messages.
