# -*- coding: utf-8 -*-
"""Project code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ENYi6Z1ZyoGs7EdqhdvTqZwfL8hbbq9P
"""

while True:
  print('Welcome to Library Resource Locator\nFind your library sources information and availability')
  print()
  print('Please choose one of the following options:')
  print(' 1. Find study room availability')
  print(' 2. Library Hours')
  print(' 3. Frequently asked questions')
  print()
  choice = input('Enter your choice (1/2/3) or enter done to exit: ')
  print()

  if choice == '1':
    while True:
      mydict = {}
      print('Study room availabilty options:')

      def booking(date, time):
        if date in mydict:
          mydict[date].append(time)
        else:
          mydict[date] = [time]
          print(f"A  study room will be booked for {date} at {time}.")

      def available_times(day):
        if day in mydict:
          booked_times = ", ".join(mydict[day])
          print(f"Booked times for {day}: {booked_times}")
        else:
          print(f"No bookings available")

      option_choice = input('Choose your day to book or enter done to exit: ')
      print()

      if option_choice == 'Sunday':
        time_choice = input('What time would you like to book?: ')
        print(booking(option_choice, time_choice))
      elif option_choice == 'Monday':
        time_choice = input("What time do you want to book?: ")
        print(booking(option_choice, time_choice))
      elif option_choice == 'Tuesday':
        time_choice = input("What time do you want to book?: ")
        print(booking(option_choice, time_choice))
      elif option_choice == 'Wednesday':
        time_choice = input("What time do you want to book?: ")
        print(booking(option_choice, time_choice))
      elif option_choice == 'Thursday':
        time_choice = input("What time do you want to book?: ")
        print(booking(option_choice, time_choice))
      elif option_choice == 'Friday':
        time_choice = input("What time do you want to book?: ")
        print(booking(option_choice, time_choice))
      elif option_choice == 'Saturday':
        time_choice = input("What time do you want to book?: ")
        print(booking(option_choice, time_choice))
      elif option_choice == 'done':
        print('Thank you for using the Library Resource Locator! \nNow returning to the main menu...\n')
        break
      else:
        print('That is not a choice, please try again or enter done to return to the main menu.\n')
      print()








  elif choice =='2':
    while True:
      print('Computer information options:')
      print(' a. UC Merced Library hours')
      print(' b. Services Desk')
      #print(' c. IT Express')
      option_choice = input('Choose (a/b): or enter done to exit: ')
      print()
      if option_choice == 'a':
        while True:
          print('UC Merced Library hours:')
          day_list = {'Sunday': '10 AM - 12 AM', 'Monday': '7 AM - 12 AM', 'Tuesday': '7 AM - 12 AM', 'Wednesday': '7 AM - 12 AM', 'Thursday': '7 AM - 12 AM', 'Friday': '7 AM - 6 PM', 'Saturday': '10 AM - 6 PM'}
          day = input('What day would you like to look for? ')
          print('Looking for', day, 'times ...\n')
          if day in day_list:
            print('The UC Merced Library is open from', day_list[day], 'on', day, '\n')
            break
          elif day == 'done':
            print('Thank you for using the Library Resource Locator! \n Now returning to the main menu...\n')
            break
          else:
            print(day, 'not found. Try capitalizing or enter done to return to the main menu.')
            print()
      elif option_choice == 'b':
        while True:
          print('UC Merced Services Desk hours:')
          day_list = {'Sunday': '10 AM - 11:45 PM', 'Monday': '7 AM - 11:45 PM', 'Tuesday': '7 AM - 11:45 PM', 'Wednesday': '7 AM - 11:45 PM', 'Thursday': '7 AM - 11:45 PM', 'Friday': '7 AM - 5:45 PM', 'Saturday': '10 AM - 5:45 PM'}
          day = input('What day would you like to look for? ')
          if day in day_list:
            print('Looking for', day, 'times ...\n')
            print('The UC Merced Services Desk is open from', day_list[day], 'on', day, '\n')
            break
          elif day == 'done':
            print('Thank you for using the Library Resource Locator! \nNow returning to the main menu...\n')
            break
          else:
            print(day, 'not found. Try capitalizing or enter done to return to the main menu.')
            print()
      elif option_choice == 'done':
        print('Thank you for using the Library Resource Locator! \nNow returning to the main menu...\n')
        break
      else:
        print('That is not a choice, please try again or enter done to return to the main menuxit.\n')







  elif choice =='3':
    while True:
      print('Frequently asked questions:')  #FAQs
      print(' a. Where do I reserve a classroom for my event/meeting? ')
      print(' b. What is the difference between a reservation and a booking? ')
      print(' c. How do I book more than 6 months in advance? ')
      print(' d. How can I add my librarian in Cat Courses? ')
      option_choice = input('Choose your day (a/b/c): or enter done to exit: ')
      print()
      if option_choice == 'a':
        print('Currently, the EMS Room Reservation System can be used to reserve non-instructional spaces campuswide. For instructional spaces, such as classrooms, you will need to reserve space with the Registrar through Ad Astra.\n')
      elif option_choice == 'b':
        print('A reservation consists of one or more bookings. A booking is one occurrence at a specific time and place.\n')
      elif option_choice == 'c':
        print('If you need to secure a space for events that require significant planning, such as commencement, please contact a Room Approver (Room Approver Directory) for spaces they approve or the EMS team (rooms@ucmerced.edu) for all other spaces.\n')
      elif option_choice == 'd':
        print("To add your Librarian to CatCoures (aka Canvas), first navigate to the People tool in the left hand navigation menu of CatCourses. Here, select Add People. In the Add People window, follow the steps outlined below: \n")
        print()
        print("Under Add user(s) by, ensure that the Email Address radio button is selected, and enter your Librarian's email address in the provided field.")
        print("Next, click on the Role drop-down menu, and select a role. We recommend Teacher, TA, or Course Designer. For information about role permissions, see OIT's site.")
        print('Click Next to confirm your role selection.')
        print('CatCourses will verify that the email address is accurate in the next window and confirm if the user is ready to be added to your course. If you receive an error, be sure to go back and verify that you have entered the email address correctly before proceeding. Once CatCourses confirms that you can add the user to the course site, click Add Users to complete the process.')
        print()
        print("Your Librarian will receive an email invitation to your CatCourses site, and once they accept it, they are added to the course.\n\n")
      elif option_choice == 'done':
        print('Thank you for using the Library Resource Locator! /nNow returning to the main menu...\n')
        break
      else:
        print()
        print('That is not a choice, please try again or enter done to return to the main menu \n')

  elif choice =='done':
    print('Thank you for using the Library Resource Locator!\nNow exiting...')
    break
  else:
    print('That is not a choice, please try again or enter done to exit.')
    print()

"""https://library.ucmerced.edu/about/library/hours"""